version: '3'
services:
 db:
   image: mysql:5.7
   volumes:
     - ./db.sql:/docker-entrypoint-initdb.d/dump.sql
   environment:
     MYSQL_ROOT_PASSWORD: '2486'
     MYSQL_DATABASE: igra_db
     MYSQL_USER: chris_user
     MYSQL_PASSWORD: '2486'
 
 wordpress:
   depends_on:
     - db
   image: wordpress:latest
   links:
     - db
   ports:
     - "8000:80"
   environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: chris_user
     WORDPRESS_DB_NAME: igra_db
     WORDPRESS_DB_PASSWORD: '2486'
   volumes:
     - './wp-content:/var/www/html/wp-content/'
 
volumes:
   db_data:
